# Site settings
title: Derek W
description: > # this means to ignore newlines until "baseurl:"
  Records logs for the work of Derek Whatley
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://derekwhatley.com" # the base hostname & protocol for your site
github_username:  djwhatle

# Build settings
markdown: kramdown
encoding: utf-8
exclude: ["README.md"]
